### ISSUE TITLE
Allow dispatchers to activate inactive users

### ISSUE THREAD

**Issue by werebus** [umts/st-pax#103]
ST requested that dispatchers be allowed to activate inactive users (but still not be allowed to deactivate them).

I don't know how good an idea this is; the request is mostly due to #102, so a quick discussion might be warranted.

But, the argument could be made that activating an old user is functionally simmilar to creating a new active user (which dispatchers _are_, pending #102, allowed to do), so...

**Comment by Anbranin** [comment]
Closing in light of most recent meeting with ST that obviates this request
