### ISSUE TITLE
Add way to visualize "needs longer ride"

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#116]
Right now the mobility device management interface will show you which kind of mobility device needs a longer ride (it's an attribute on the object), but there's no way to easily see that from the passenger index.
It was requested that there be a way to see at-a-glance, specifically with styling and _not_ with another column, which passengers need more than a single ride slot.

**Comment by Anbranin** [comment]
Someone please tell me what a good style is for this. An outline? Can't be another color, those are exclusionary. 
I'm thinking, like they suggested in the meeting, outlining their mobility device with black. Easy peasy styling...

**Comment by werebus** [comment]
I think whatever you do, you'll want to do it to the whole row.

Bold or colored text?  Or [how about some nice stripes](https://jsfiddle.net/5n4a98eb/)?

**Comment by Anbranin** [comment]
Whatever _I_ do? You just did it, except in a jsfiddle instead of a PR >:(

P.S. I love the stripes

**Comment by Anbranin** [comment]
Make sure whatever you add prints

**Comment by Anbranin** [comment]
#145 also helps cover this.
