### ISSUE TITLE
Add checkbox for "has doctor's note" and conditional validation on expiration date

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#118]
Right now an expiration date existing is how we determine whether a passenger has a doctor's note. It's really the only thing about a doctor's note.
But, the supervisors would like a way–to more easily than that–visually determine who has a doctor's note (especially now that the expiration date could be filled in with the date 3 days from registration).
I envision this: The checkbox "has doctor's note" is on the passenger show/edit form. "I exist" is a property on DoctorsNote (let me explain...), so that we can easily conditionally validate that the expiration date exists if the "has doctor's note" box is checked on the passenger page.

**Comment by werebus** [comment]
>  "I exist" is a property on DoctorsNote

Why, though? Isn't there already an idiomatic way to determine if a thing exists? If a `Passenger` only _has_ a `DoctorsNote` when they, you know _have_ a doctor's note, then you can just make the expiration date a required field always, right?

**Comment by Anbranin** [comment]
Okay, so the checkbox "has doctor's note" would cause the creation of a doctor's note, thus rendering the "expiration date" a required field. That is far easier.
