### ISSUE TITLE
Add status to passengers "Archived"

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#120]
Passengers are marked inactive (active: false) when the expiration date for the doctor's note has passed. They're colored grey on the index page the moment the date passes, and then actually marked inactive in a `whenever` task every night and then can only be seen by clicking the "show inactive" filter on the index page.

However, it is now desired by the STSPVs that passengers actually have three states: "Active" - they need rides currently.
"Inactive" - their doctor's note has expired, but it could be an oversight and they could still need rides. After all, people get extensions a lot. They could easily be reactivated and should remain on the main index page, just a different color.
"Archived" - The passenger may come back at some point if they ever need our services again, but they probably (hopefully!) won't. Archived is a more "for real inactive" state, describing the differences between "the doctor's note just expired and they could legitimately still need our services and we should check with them" and "they healed up or moved away and don't need rides any more indefinitely."

The plan is that the STSPVs will manually move people to an archived state on whatever kind of regular basis they wish. Thus, the whenever task can be removed.

Concrete things that need to happen:

- [x] a new nav-tab on top that shows archived passengers on their own page
- [x] remove the "inactive" checkmark on the index page
- [x] remove the checkbox "show inactive" filter on the index page
- [x] remove the whenever task that makes passengers inactive
- [x] make an "archive" button - and conversely, a "de-archive" button.

Brainstorming:

I suspect in the end that there will be 3 or 4 statuses for passengers, now that we're implementing "archived" and will also soon implement "pending" - this is because passengers will fill out their own registration forms soon. I believe it makes sense to have "status" be an enum. So, "inactive" may not be necessary, because "inactive" should now be defined by someone having a doctor's note with an expiration date before today, and the only place that's necessary to display is on the index page. They'll be grey and that can be computed with a model method `#inactive`.

HOPE THIS ALL MAKES SENSE

**Comment by werebus** [comment]
Just a side note, if you remove the Whenever task, you will have removed _all_ the Whenever tasks. May as well also remove Whenever itself too.
