### ISSUE TITLE
Search for existing passengers when making new ones - start tracking spire IDs

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#121]
Related to #120 
In the current implementation of this database (I think it's a google spreadsheet, or maybe they're still using the access database) there are multiple passengers with the same information because once a passenger is inactive, they disappear from view--and searching for them is harder than just creating a new passenger. Lots of duplicate data.
The idea now is to start storing Spire IDs (at least of new passengers, existing ones fitting into the new schema are a problem someone will have to tackle, or maybe not) and when a new passenger is being created, our code will search the existing passengers (archived or not) and if a passenger already exists with that Spire ID, a friendly message should pop up and redirect the user to the page for that passenger.
It would be best if this happened not upon submit when the user has already typed in all sorts of information, but with an Ajax call triggered by filling in (and de-focusing) the Spire ID field.
A user could also search the "archived" page for this passenger, but implementing a fancy search function is an enhancement to think about, and command-F also works.

**Comment by Anbranin** [comment]
Idea for spire ID, since it really should be required, is to make it required: true except for the case that it's overridden (some older passengers who can be "grandfathered in" to the new system. Yes, this will require a new boolean. Can be removed later when those passengers aren't in the system any more (that is, when "Passenger.where('spire_id is null')" returns 0

**Comment by werebus** [comment]
Is that needed? It seems like if a person is editing a `Passenger`, they either are the person in question or are in contact with them and could ask.

This might be one of those situations where the case that validations aren't run on existing data is an _advantage_.

**Comment by Anbranin** [comment]
>  It seems like if a person is editing a Passenger, they either are the person in question or are in contact with them and could ask

I didn't think about this. You're right and that makes it a lot simpler. Of course, as with the email issue, we'll see what happens in production.
