### ISSUE TITLE
automatically check the 'active' box when editing any passenger

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#137]

**Comment by werebus** [comment]
Prompt when saving perhaps?  If it's "automatic", why even have a checkbox?

**Comment by Anbranin** [comment]
The request has been revised to: When editing an archived passenger, have the 'active' checkbox be automatically checked.
 99% of the time editing an archived passenger is because a dispatcher is reentering their info, but the admins would like to retain the ability to edit an archived passenger and leave them archived--but in that case they'd be paying attention.
They would like to minimize mistakes for the dispatcher to make when entering passengers.

**Comment by werebus** [comment]
:woman_shrugging: Sure.
