### ISSUE TITLE
Notice isn't used

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#14]
Most controller actions end with a `notice:`, but I don't see them appear anywhere in the layout.

**Comment by dfaulken** [comment]
Should wait to work on this pending the layout changes in #17.

**Comment by dfaulken** [comment]
@AkivaGreen, am I correct in noticing that you are taking care of this in #21?

**Comment by AkivaGreen** [comment]
Yes, they were in the individual view files. Since, it is being used in my feature spec for passenger management I moved it to the most logical place it could be.
