### ISSUE TITLE
render line breaks in note box on dispatch log page

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#142]
when entering in a dispatch log, pressing the enter key makes a line break. That line break is _not_ rendered in the final note, which isn't ideal. Line breaks should be persisted and rendered in the final note.

**Comment by werebus** [comment]
To clarify a bit,  The line breaks _are_ rendered — they make it to the browser — it's just that white space within the DOM isn't meaningful. Browsers collapse it into a singe space.

![2019-10-09_13-17](https://user-images.githubusercontent.com/240275/66504479-28fad800-ea97-11e9-8d34-7bb2a81326b7.png)

If you want literal whitespace, you can use [a `<pre>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) Or some sort of rich text formatter (markdown? ActionText?).

**Comment by Anbranin** [comment]
They didn't think supporting rich text was necessary, but it'd be nice if dispatchers could break relevant portions into paragraphs. I'll have to look at what pre tags are.

**Comment by werebus** [comment]
`<pre>` tags are usually formatted in monospace font and you lose line wraps too (so each paragraph will be one long line).

That said, I just leaned a new [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space). It looks like you can just say `white-space: pre-line;` to [get what you want](https://jsfiddle.net/1sb2yLt4/)
