### ISSUE TITLE
add "copy emails of filtered list to clipboard" button next to "print these filters" button

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#144]
Admins regularly have to email passengers in bulk with announcements--they'd like a button to "copy all emails to clipboard" much like we have in umasstransit with the directory.

**Comment by werebus** [comment]
Just FYI, since we wrote that feature on umasstransit.org the web has made interacting with the clipboard [way better](https://clipboardjs.com/).

**Comment by Anbranin** [comment]
I just implemented some [shiznit](https://github.com/umts/umaps-rails/blob/8c7342e662475bef0b350a77f0b61788591a1362/app/assets/javascripts/ui.js.erb#L104-L115) on umaps-rails using bootstrap and copying from @jforgue's work on screaming dinosaur, but this seems also cool.

**Comment by Anbranin** [comment]
Sometimes the ST Supervisor needs to email everyone on the archive page as well, so any functionality added to the index should be added there as well.
@Tanvish this was requested again today so it's moved up to higher priority. I got them the emails they needed off the command line but it'd be nice if they didn't have to ask me.
