### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#154]
I told all the dispatchers I would.

**Comment by werebus** [comment]
Since we've mastered opening GitHub issues with other repos, maybe we want to that with submitted feedback.

**Comment by Anbranin** [comment]
damn right. I think for the sake of expediency I'll put in an "email IT" button but it seems like it shouldn't be that hard to copy what's on round-three n do a github thingy

**Comment by werebus** [comment]
I started working on GitHub integration, I might finish it today.

**Comment by Anbranin** [comment]
Nice
