### ISSUE TITLE
Change printout to letter paper

### ISSUE THREAD

**Issue by werebus** [umts/st-pax#176]
Because we try to make it that way:

https://github.com/umts/st-pax/blob/526add8ad27d2a5af2de81be00300f9dc783ca4c/app/pdfs/passengers_pdf.rb#L8

If, as I suspect, they usually go on landscape _letter_ paper, that should be changed because the two papers don't share an aspect ratio.

**Comment by Anbranin** [comment]
They definitely don't _want_ to print them on 11x17. There was a feedback created by a dispatcher a few days ago that I assumed would make an issue but I guess it didn't happen--the table doesn't flow from one page to another very well and cuts off rows right in the middle. I happened to pass her desk and she was able to show me, so I'll make an issue about it.

I can't say for certain she filled out a feedback about it but I asked her if she did and she said yes.
