### ISSUE TITLE
Passenger table doesn't flow well from one page to another

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#177]
Rows get split in the middle if they flow onto the next page.

**Comment by werebus** [comment]
Have you confirmed this behavior? I can't.

[All passengers 2019-11-14.pdf](https://github.com/umts/st-pax/files/3847390/All.passengers.2019-11-14.pdf)

**Comment by Anbranin** [comment]
It doesn't happen on the PDF, it only happens under one specific scenario, and that is printing it out on non-tabloid-size paper. If you attempt a print with 8.5x11 you'll get this behavior. So I think closing #176 will close this issue.

**Comment by werebus** [comment]
OK so.... duplicate of #176?

**Comment by Anbranin** [comment]
Yeah I guess except this was describing a specific unpleasant symptom that's all
