### ISSUE TITLE
Site feedback doesn't create issues

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#179]
If filing this bug report works, it's not a bug. LOL

**Comment by Anbranin** [comment]
OK so the dispatcher wasn't being truthful when she told me she'd submitted site feedback I guess.

**Comment by werebus** [comment]
Welp...

**Comment by Anbranin** [comment]
But the "show" page is this: https://api.github.com/repos/umts/st-pax/issues/179

**Comment by Anbranin** [comment]
I clicked on it to see, and I was like yep that's some JSON. So that's maybe a bug.
