### ISSUE TITLE
Add new passenger/edit existing user issue

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#187]
When an existing passenger's spire number is entered in the "add new passenger" form, none of the fields get populated, an error message is just given.

**Comment by werebus** [comment]
Talked to the dispatcher: user error.

**Comment by werebus** [comment]
More information: the dispatcher assumed that you would "have to press enter" in order to get the existing passenger check to work.  But pressing enter submits the form, leaving him with the "dumb" validation failure, "Passenger Spire has already been taken."
