### ISSUE TITLE
Record "registerer" when registering a passenger

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#209]
Hello. I needed to see which dispatcher registered a passenger today because there was a mistake with the date. When I looked to see who it was, it said "Registering Dispatcher: Unknown". I noticed that it says this for all passengers. If we could see which dispatchers are registering passengers that would be super helpful!

[71](https://st-pax.admin.umass.edu/users/71)

**Comment by werebus** [comment]
Yup. That field is only populated by the Access database import.

**Comment by Anbranin** [comment]
>:|
