### ISSUE TITLE
Why do users need emails?

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#23]
I don't see them used anywhere.

Since users missing them are "invalid" from Access, may as well remove the attribute and validation if we don't need it for anything.

**Comment by Anbranin** [comment]
We aren't importing users from Access--if you mean passengers, then we do need to display an email--it's used to send passengers a brochure upon registration at the very least (and I think other things but can't remember specifics ATM). However, if there's a validation in place for presence, we should remove it if the import process will fail. We can validate format conditionally. We should ask ST if, going forward, it should be a presence validation.

**Comment by dfaulken** [comment]
We are importing users from Access. There's a list of dispatchers. Should I not be doing that?

**Comment by Anbranin** [comment]
I was unaware that there is a list of dispatchers in the access database. We should ask ST if the list is current or even used for anything.
If it is, we can use it. If not, we can figure out another way to create users (A SQL dump from round 3 of the result of selecting users with the ST dispatch qualification comes to mind, and would probably be most up-to-date)

So yes, let's remove the attribute, in any case. It is indeed unused.

**Comment by dfaulken** [comment]
I'm sure they're equally up to date. One needs both in order to work an ST dispatch shift. I've already written the users import, anyway.

I'll remove the attribute.
