### ISSUE TITLE
Passengers can't self register: fcIdNumber already contains "@umass.edu"

### ISSUE THREAD

**Issue by werebus** [umts/st-pax#257]
As we get it from Shibboleth, the `fcIdNumber` in the session variables contains the string `<spire_number>@umass.edu`

(@tanvish was on to something [here](https://github.com/umts/st-pax/pull/248/files/e0309bc6ec65336ac2f73adb23a44ad02c3a7f44#r549524821))

I noticed this because I had temporarily deactivated my user in production and got this on the self-registration page:

![2021-01-26_15-02](https://user-images.githubusercontent.com/240275/105898546-92359000-5fe7-11eb-9635-cd8c32c8fefe.png)

And then:

![2021-01-26_15-05](https://user-images.githubusercontent.com/240275/105898839-eb9dbf00-5fe7-11eb-8bab-25120fea8eac.png)

**Comment by Anbranin** [comment]
I super thought shibboleth gave us only the number, but it's clear from elsewhere in the code that that's not the case.
