### ISSUE TITLE
Add missing attributes to Passenger, and import

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#27]
The following attributes are present in Access but don't exist in our passengers table:

+ student ID
+ UMass status (student, alumni, etc.)
+ dispatcher who registered them

For temporary passengers:

+ whether they're registered with Disability Services
+ "has brochure" (🤷‍♂️)

Do we need them?

**Comment by Anbranin** [comment]
I'm gonna copy and paste this GH issue and send it as an email to STSPV lol

**Comment by Anbranin** [comment]
"has brochure": references whether or not the dispatcher emailed them the st passenger brochure that contains our rules / regulations / directions for use. It's required that we send all temp passengers a brochure when they register.

**Comment by dfaulken** [comment]
Andrew came by and said yes to all.

**Comment by dfaulken** [comment]
We're not importing temporary passengers, but I'll add the attributes.

**Comment by dfaulken** [comment]
Still need to make them shown somewhere in the views.
