### ISSUE TITLE
View template reloading doesn't work for `app/views/log/*`

### ISSUE THREAD

**Issue by benmelz** [umts/st-pax#358]
@aflam745 discovered while working on #336 that when editing `app/views/log/index.haml`, any changes made aren't reflected until a full server restart.

On a hunch, I thought that perhaps `log/` has a special rule that makes it ignored by the rails' file-watcher-code-reloading system aaaand when I rename the folder in development, things start working again.

`log` is a bad name for this controller/view system anyways - the model is named `LogEntry`.

**Comment by werebus** [comment]
https://github.com/guard/listen/blob/fd85e1cb2375767e3cbc4b5743ff50061e8a6c75/lib/listen/silencer.rb#L14
