### ISSUE TITLE
Move from `will_paginate` to `kaminari`

### ISSUE THREAD

**Issue by benmelz** [umts/st-pax#363]
`will_paginate` is no longer maintained, `kaminari` is the way forward

**Comment by werebus** [comment]
I mean, Will Paginate release version 4.0.0 2 weeks ago...

**Comment by benmelz** [comment]
I misremembered, it's in maintenance mode (as for the major version bump, it seems to be just for dropping integration support for various older libraries).

Anyways I still stand by switching eventually, as we're on `kaminari` on round-three/umaps, has a larger market share, is a bit more flexible etc etc.
