### ISSUE TITLE
Remove phone from User

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#38]
umasstransit.org is the method through which employees get in contact with one another, I think.

**Comment by Chauce** [comment]
The original user's model was built when we didn't know there was an easy way to make a dev login to test admin/non admin users. I think we just never bothered to run a migration to remove superfluous things from users.

Actually, aren't the only necessary things in there 'name', 'spire', and 'admin'?

**Comment by dfaulken** [comment]
And `active`.

Sounds like we can remove `phone` then.
