### ISSUE TITLE
CSV of Name, Longer rides, Permanent

### ISSUE THREAD

**Issue by sherson** [umts/st-pax#404]
Dispatchers need a CSV export with these columns for _Active_ passengers:
 
* Name
* Longer rides
* Permanent

They'd like an `Export` button next to `Copy Emails`.

Replaces #384

**Comment by werebus** [comment]
FWIW, it will probably be slightly easier to have an export for whatever list of passengers you're looking at, rather that only allowing it for active passengers.

**Comment by werebus** [comment]
Here's a fun titbit: Did you know that submit buttons can have `formaction` attribute that specifies where the form submits to? So, for example, the [filter form](https://github.com/umts/st-pax/blob/63114cd33d967ffbd6b17aa57a17b4dfbfd9db8f/app/views/passengers/_filters_and_key.html.haml#L3-L12) (where the "Print" button already is) could look like:

```haml
= bootstrap_form_tag method: :get do |f|
  // Etc, etc, etc
  = f.submit 'Print', formaction: passengers_path(format: :pdf)
  = f.submit 'Export', formaction: passengers_path(format: :csv)
```
