### ISSUE TITLE
s/Recently/Within Grace Period

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#42]
The code and views use the word "recently" a lot to mean "within the grace period" for expiration dates of doctor's notes. This tripped me up during a refactor to the point where [we thought other things were broken](https://github.com/umts/st-pax/issues/40), so let's remove the ambiguity and replace the word "Recently" with "Within Grace Period" across the site (code included).

**Comment by mboneil10** [comment]
I love how you titled this.

**Comment by mboneil10** [comment]
"Recently" can be found next to "expired", so I'll also change that accordingly.
Example: `Recently Expired` should become `Expired Within Grace Period` (not `Within Grace Period Expired`)
