### ISSUE TITLE
Show mobility device in passengers table?

### ISSUE THREAD

**Issue by dfaulken** [umts/st-pax#44]
If we show the mobility device in the passengers table, then we show all of their attributes.

So perhaps we can remove the 'Show' link entirely, except for admins, who should be able to see the additional attributes in #27.

Seems like that's a thing dispatchers would want to just see without having to click through every time someone calls.

**Comment by Anbranin** [comment]
If a dispatcher can register a passenger and fill in those attributes, it doesn't make sense to then hide them from view from any other dispatchers.
It does indeed make sense to show all the attributes needed to schedule rides in the table so one doesn't have to click through, though.

**Comment by dfaulken** [comment]
Good point.

So we should add the mobility device to the table, but retain the 'Show' link.
