### ISSUE TITLE
Better sort order arrows

### ISSUE THREAD

**Issue by AkivaGreen** [umts/st-pax#60]
I'm sorting by Name, however, it looks like I'm sorting by Mobility Device instead. I would prefer better placement for those arrows so people don't get confused when using the sort functions.
![screen shot 2017-08-31 at 12 34 25 pm](https://user-images.githubusercontent.com/15308734/29934350-c95a5d0a-8e48-11e7-8b68-70a558df8031.png)

**Comment by mboneil10** [comment]
FWIW, the arrows are behaving "normally" (turn blue and change orientation) only when one sorts by Expiration Date.
