### ISSUE TITLE
Anyone can manage users

### ISSUE THREAD

**Issue by werebus** [umts/st-pax#67]
I am not an admin in production, but I was able to see and edit a person's Spire ID **and** make them an admin.

**Comment by dfaulken** [comment]
Having trouble replicating this one. In development as a dispatcher I do get an access denied. The application controller has `access_control` by default as a `before_action` and it isn't skipped in that controller.

**Comment by werebus** [comment]
Welp, I'm a little lost.  I wonder if this had anything to do with me having an admin user, resetting the DB, then not having an admin user?

I can't see how it would.... but I appear to not be able to admin stuff anymore?
