### ISSUE TITLE
Navigating "back" to passengers index creates duplicate data table headers and footers

### ISSUE THREAD

**Issue by werebus** [umts/st-pax#71]
1.  Load the `PassengersController#index`
2.  Go somewhere else
3.  Press the back button
4.  Repeat steps 2 and 3 if you like.

![screenshot_2017-09-13_13-27-31](https://user-images.githubusercontent.com/240275/30397521-2af08db2-989b-11e7-817a-ea8638f5eead.png)
![screenshot_2017-09-13_13-27-50](https://user-images.githubusercontent.com/240275/30397520-2aeaaaf0-989b-11e7-8003-e5f1d5c8ffba.png)

Yet another turbolinks/datatables conflict of some kind?  I'd be curious if #65 might fix this too?

**Comment by Chauce** [comment]
I can't seem to recreate the issue on my end after the most recent pull from `master`. Can anyone else confirm one way or another if this is still a problem?

**Comment by werebus** [comment]
Yes, it is.

**Comment by mboneil10** [comment]
Can confirm:
<img width="1232" alt="screen shot 2017-09-24 at 10 12 30 am" src="https://user-images.githubusercontent.com/19267771/30783441-e6947d26-a110-11e7-92c4-cceaad982473.png">
<img width="1237" alt="screen shot 2017-09-24 at 10 11 37 am" src="https://user-images.githubusercontent.com/19267771/30783439-dbd8ba0a-a110-11e7-83a0-f38c27704f7a.png">

**Comment by Chauce** [comment]
As an update on the status of this issue ... I have some coffescript courtesy of the datatable help forum that does in fact work to fix this issue. But I haven't gotten to a point where I understand either coffeescript or datatables enough to be able to tell you why.

**Comment by Chauce** [comment]
Not getting this behavior anymore ... instead, when I try to navigate back, I get this error:

> DataTables warning: table id=passengers - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by Chauce** [comment]
I'd say close this, and open up a new issue for the "Cannot reinitialize DataTable" warning

**Comment by werebus** [comment]
FWIW, in production, Javascript is not working at all for me at the moment.  So there is no way to know if this issue still exists.

![image](https://user-images.githubusercontent.com/240275/41613937-0ef3f030-73c5-11e8-88a1-7fcbde5f049a.png)

**Comment by werebus** [comment]
In reviewing #126 (which fixes the error I commented above), I determined that this, in fact, was *not* fixed.

**Comment by Anbranin** [comment]
<iframe src="https://giphy.com/embed/12XMGIWtrHBl5e" width="480" height="392" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/the-office-no-steve-carell-12XMGIWtrHBl5e">via GIPHY</a></p>

**Comment by Anbranin** [comment]
![nogodno](https://user-images.githubusercontent.com/9645316/65712516-36f73480-e065-11e9-9b83-455153af310b.gif)
