### ISSUE TITLE
Link is Gray but not Disabled

### ISSUE THREAD

**Issue by mboneil10** [umts/st-pax#83]
I noticed that the `visited links` are [gray](https://github.com/umts/st-pax/blob/master/app/assets/stylesheets/application.scss#L61). Whenever I see _anything_ on a page that is grayed out, I automatically think it's disabled. Compare the top two passengers' `view` and `delete` to the bottom one:
<img width="1238" alt="screen shot 2017-09-17 at 10 18 19 am" src="https://user-images.githubusercontent.com/19267771/30521680-9617125c-9b91-11e7-8902-8075801e9ac3.png">

The reason I bring this up is because we have gray-on-gray:
<img width="1230" alt="screen shot 2017-09-17 at 10 28 28 am" src="https://user-images.githubusercontent.com/19267771/30521788-16857f68-9b93-11e7-8b09-0a98dadec572.png">

And that same color indicates that a button is disabled:
<img width="234" alt="screen shot 2017-09-17 at 10 21 41 am" src="https://user-images.githubusercontent.com/19267771/30521703-05525ed8-9b92-11e7-8bf5-f5e921e55912.png">

My fix would be to remove styling on visited links. Or maybe remove disabled buttons from the user. Possibly both. Could be a personal problem?

**Comment by dfaulken** [comment]
You're right. It's not too relevant for this app whether you happen to have looked at someone's info before, since the dispatcher computer is shared, so it makes sense for visited links to look like any other links.
As for disabled content, do we have any besides pagination buttons?

**Comment by mboneil10** [comment]
If I search `666`  😖 , it only appears in `404.html`, `422.html`,`500.html`, and `application.scss`. So the pagination buttons are colored gray by default. Means I'll have to poke around to find the others, if any, right?

**Comment by dfaulken** [comment]
I'm confused, you ask here about disabled content. Should be sufficient to `grep -r disabled app/views`, no?

**Comment by mboneil10** [comment]
Ah, yes. That would make sense. Thanks @dfaulken

**Comment by mboneil10** [comment]
Sorry, assigned myself to the wrong thing

**Comment by mboneil10** [comment]
Looks like the only things besides buttons are fields and checkboxes.

**Comment by dfaulken** [comment]
So what's your take on what needs to be done in to resolve the issue?

**Comment by mboneil10** [comment]
Remove color styling from visited links and disabled buttons from user's view.
