### ISSUE TITLE
Enhance the reactivation warning

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#9]
Current functionality: When a user checks the "active" button to reactivate a passenger, there is a javascript popup warning them that if the expiration date is not also updated the passenger will become deactivated again at 4:30 AM.

Problems: If a warning pops up every time a passenger is reactivated, alert fatigue can occur. Alerts when something is not actually wrong or going to go wrong is undesirable.

Desired functionality: Write a Javascript function that checks the expiration date value in the field and whether or not it is in the future. If the date is in the future, no warning. If the date is today or before, warn the user. That way, they only get a warning if they have done something that may cause problems in the future, thus preventing alert fatigue.

**Comment by dfaulken** [comment]
I don't see an "Active" checkbox while editing a passenger.

**Comment by Anbranin** [comment]
It only shows if the current user is `admin`.
