### ISSUE TITLE
Interface to create PDF of current temporary passengers

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#92]
The Dispatchers are used to having a printout of temporary passengers they can quickly check when people call in.

We should create a PDF of these - their names and the expiration dates of their doctor's notes in separate columns.

The passengers whose doctors notes are expiring soon (3 days? we can check with Andrew) should be highlighted in some way (let's try not to do colors, maybe shading?)

**Comment by dfaulken** [comment]
Isn't a listing of temporary passengers the point of the website?

**Comment by Anbranin** [comment]
Yes. Andrew came in and requested it. *shrug*

**Comment by Anbranin** [comment]
Could talk to him.

**Comment by werebus** [comment]
:zap: Avia asked about this at the staff meeting yesterday.

Also, we *did* have a conversation with ST about why this is needed. The rationale was that **ROs** need to see someone's temporary status, and they don't have logins to the site. We could go the route of making the site usable by them, but that might be of limited utility for read-only access to a list of people.

**Comment by dfaulken** [comment]
> ROs need to see someone's temporary status, and they don't have logins to the site

IMO this might be a good use case for developing an API between this site and umasstransit.org, then, given that dispatchers are people who are by definition already using another of our websites.

But in the short term, agreed that a PDF is the path of least resistance.

**Comment by jforgue** [comment]
Is this something that should be handled with `prawn`?

**Comment by Anbranin** [comment]
I'd choose prawn based on my familiarity with it, why, did you have another way to generate PDFs you wanted to try?

**Comment by jforgue** [comment]
No, I've just never done this before.

**Comment by Anbranin** [comment]
Assigning this to @Chauce because they need something to work on but @jforgue if you're interested, feel free to pair.
